# Useful-Saves configuration file, maked by FlowArg, options created by Ama <3
# Go to README.MD on github for more information !
# -> Ama's github repository : https://github.com/FlowArg/Useful-Saves/ (MOD)
# -> FlowArg's github repository : https://github.com/FlowArg/Useful-Saves/ (PLUGIN)

################################## USEFUL-SAVES CONFIGURATION ##################################
#                                                                                              #
#                                                                                              #
#                                     COMMON CONFIGURATION                                     #
#                                                                                              #
#                                                                                              #
################################## USEFUL-SAVES CONFIGURATION ##################################

# Print Useful Saves messages in chat ?
printMessage: true

# Define a TimeZone if server clock mismatch players clock
# Automatically generated by default
timeZone: Europe/Paris

# Define a json formatted cron task to save/load
# If "enableTaskOnServerStart" is enabled task will be loaded.
cronTaskObject: '{}'

# Define maximum created backups
# "-1" = unlimited saves
# Range: > -1
maximumSavedBackups: -1

# Enable the previous saved scheduled task on server start ?
# Ensure "cronTask" is not empty or null
enableTaskOnServerStart: true

# Define a backup folder
backupsFolder: ./backups

# Process save task if no player connected ?
saveIfServerEmpty: true

# Define a list of files or folder to save on saving process
# Use absolute path !
savedFileWhitelist: 
    -./logs
    -./config

# Defined to delete oldest backups if maximum saves are reach
# Used if "maximumSavedBackups" are defined
deleteOldOnMaximumReach: false